config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  resources :visits do
    post :photo, on: :collection
    get :audio
    post :audio_update
    get :questions
    post :questions_update
    get :result
  end
  devise_for :users
  root to: 'visits#index'

  match '/about', to: 'pages#about', via: :get

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/visit.rb
class Visit < ApplicationRecord
  mount_uploader :photo_file, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end


end

app/controllers/visits_controller.rb
class VisitsController < InheritedResources::Base
  respond_to :js, :html, :json

  def index
    @visit = Visit.create!(uuid: SecureRandom.uuid)
  end

  def photo
    @visit = Visit.where(uuid: visit_params[:uuid]).first
    @visit.update(photo_file: visit_params[:photo_file])
    response = PredictImageAgeService.new(@visit).call
    @visit.update(predicted_image_age: response.parsed_response["prediction"])
    redirect_to visit_audio_path(@visit.id)
  end

  def audio
    @visit = Visit.find(params[:visit_id])
    render :audio
  end

  def audio_update
    @visit = Visit.find(params[:visit_id])
    @visit.update(audio_threshold: visit_params[:audio_threshold])
    response = PredictAudioAgeService.new(@visit).call
    @visit.update(predicted_audio_age: response.parsed_response["prediction"])
    redirect_to visit_questions_path(@visit.id)
  end

  def questions
    @visit = Visit.find(params[:visit_id])
    render :questions
  end

  def questions_update
    @visit = Visit.find(params[:visit_id])
    @visit.update(visit_params)
    if @visit.predicted_audio_age.present?
      audio_age = @visit.predicted_audio_age
    else
      audio_age = 1
    end
    if @visit.predicted_image_age.present?
      image_age = @visit.predicted_image_age
    else
      image_age = 1
    end
    est_age = (audio_age + image_age) / 2
    est_age.round
    age = @visit.age
    if age.present?
      age.round
    else
      age = 1
    end
    result = 'good'
    if est_age.between?(age - 3, age + 3)
      result = 'good'
    end
    if est_age.between?(age - 5, age + 5)
      result = 'bad'
    end
    if (age > est_age + 5) || (age < est_age - 5)
      result = 'ugly'
    end
    @visit.update(result: result, estimated_age: est_age)
    redirect_to visit_result_path(@visit.id)
  end

  def result
    @visit = Visit.find(params[:visit_id])
  end

  def visit_params
    params.require(:visit)
          .permit(:person,
                  :photo_file,
                  :visit_dttm,
                  :predicted_audio_age,
                  :predicted_image_age,
                  :audio_threshold,
                  :audio_error,
                  :uuid,
                  :nationality,
                  :gender,
                  :mother_origin,
                  :father_origin,
                  :birthday_year,
                  :birthday_month,
                  :hearing_impaired,
                  :age)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <p>&copy; 2017 AdvantAge.</p>
    <ul class="list-inline">
      <li class="list-inline-item">
        <a href="/about">About</a>
      </li>
    </ul>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
  <div class="container">
    <a class="navbar-brand js-scroll-trigger" href="/"><span class='black'>Advant</span><span class='red'>Age</span></a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fa fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="/about"><span class='black'>About</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#download"><span class='black'>Picture</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#features"><span class='black'>Sound test</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#contact"><span class='black'>Help us improve</span></a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Advantage</title>
   <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="page-top">
    <%= render partial: 'layouts/navbar' %>
    <%= yield %>
    <%= render partial: 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<section class="contact bg-primary">
  <div class="container">

    <h1>Who we are?</h1>
    <p>The Advantage Humanitarian project originated at the Humanitarian Hackathon at CERN in Geneva on the 6th-8th October 2017.</p>
    <br/>
    <h1>Why are we doing this?</h1>
    <p>The UN Convention on the Rights of the Child (CRC) defines a child as any human being under the age of eighteen years unless the majority is attained earlier under the applicable legislation (Article 1). The CRC and many national legal systems provide adequate protection and specific rights for minors in many areas. The recognition of the minority of a person is therefore essential to have access to these specific rights and to enhanced protection.</p>

    <p>However, many children do not have recognized official documents to establish their date of birth (due to deficiencies in the registration of births in their country of origin, loss of identity papers or recognition by foreign authorities of their official documents). These children are unlikely to be considered as adults by the authorities, which can have dramatic consequences on the adequacy of their care.
    </p>

    <p>If a minor is considered to be an adult, the risks are all the higher or even inevitable in relation to such risks incurred by adults, whether they are subjected to inappropriate treatment in procedures that do not take into account situation, age or maturity: "In the absence of documents attesting to their age, children are more vulnerable to enrollment in the armed forces, dangerous forms of work or early marriage.</p>

    <p>  They are also more likely to be treated as adults, rather than as children or minors, in judicial proceedings or seeking international protection as asylum-seekers ". These various situations can have irreversible negative consequences to the detriment of respect for the rights of the child, his physical development and his psychological well-being. Through its presence on the ground and the projects put in place, Terre des hommes is directly witness to these situations at risk for young people.</p>

    <br/>

    <h1>What are we doing with your picture and information?</h1>
    <p>Your data (pictures, month of birth and country of origin) will be stored in a secure network and will in no case be shared with any third party. The information provided will not allow tracking your information back to you.</p>


</section>

app/views/visits/_landing.html.erb
<section class="features" id="landing">
  <div class="container">
    <div class="row">
        <div class="col-md-4 col-xs-12">
          <br/><br/>
          <br/><br/>

          <h1 class='red'>Age can determine one's destiny.</h1>
          <br/><br/>
          <h2>Help us determine it with dignity!</h2>
          <br/>
           <a href="#download" class="btn btn-outline btn-xl js-scroll-trigger">Get Started</a>
        </div>
        <div class="col-md-8 col-xs-12">
          <%= image_tag 'landing.jpeg', class: "img-responsive landing-img"  %>
        </div>
        </div>
      </div>
    </div>

  </div>
</section>

app/views/visits/_questions.html.erb
<section class="download bg-primary text-center" id="download">
  <div class="container">
    <div class="row">
      <div class="col-md-8 mx-auto">
        <h2 class="section-heading">Tell us about yourself</h2>
        <%= simple_form_for @visit,
                            remote: true,
                            id: 'question-form' do |f| %>
          <div class='row'>
            <div class='col-6'>
              <%= f.input :birthday_month, label: 'You were born (month)' %>
            </div>
            <div class='col-6'>
              <%= f.input :birthday_year, label: 'You were born (year)' %>
            </div>
          </div>
          <%= f.input :nationality %>
          <%= f.input :gender, as: :radio_buttons, collection: ["Male", "Female","Other"], label: false %>
          <div class='row'>
            <div class='col-6'>
              <%= f.input :mother_origin %>
            </div>
            <div class='col-6'>
              <%= f.input :father_origin %>
            </div>
          </div>
          <%= f.input :hearing_impaired, as: :radio_buttons, collection: ["Yes", "No"] %>
          <%= f.hidden_field :uuid %>
          <%= f.submit %>
        <% end %>

        <div class="badges">
          <a class="badge-link" href="#"><img src="img/google-play-badge.svg" alt=""></a>
          <a class="badge-link" href="#"><img src="img/app-store-badge.svg" alt=""></a>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/visits/_result_bad.html.erb
<div class="card">
  <div class="card-body text-left">
    <h4 class="card-title">Our AI estimates your age at <%= @visit.estimated_age %> years.</h4>
    <p>Your Age:&nbsp;<%= @visit.age %></p>
    <p>Result Selfie:&nbsp;<%= @visit.predicted_image_age %></p>
    <p>Result Audio:&nbsp;&nbsp;<%= @visit.predicted_audio_age %></p>
    <div class='text-center'>
      <%= image_tag '005-quiet.png', class: 'img-fluid mx-auto'  %>
    </div>
    <br/>
    <p>Whoops, learning is a long process, right?</p>
  </div>
</div>

app/views/visits/_result_good.html.erb
<div class="card">
  <div class="card-body text-left">
    <h4 class="card-title">Our AI estimates your age at <%= @visit.estimated_age %> years.</h4>
    <p>Your Age:&nbsp;<%= @visit.age %></p>
    <p>Result Selfie:&nbsp;<%= @visit.predicted_image_age %></p>
    <p>Result Audio:&nbsp;&nbsp;<%= @visit.predicted_audio_age %></p>
    <div class='text-center'>
      <%= image_tag '002-wink.png', class: 'img-fluid mx-auto'  %>
    </div>
    <br/>
    <p>Not bad for a 3 day old learning machine...</p>
  </div>
</div>

app/views/visits/_result_ugly.html.erb
<div class="card">
  <div class="card-body text-left">
    <h4 class="card-title">Our AI estimates your age at <%= @visit.estimated_age %> years.</h4>
    <p>Your Age:&nbsp;<%= @visit.age %></p>
    <p>Result Selfie:&nbsp;<%= @visit.predicted_image_age %></p>
    <p>Result Audio:&nbsp;&nbsp;<%= @visit.predicted_audio_age %></p>
    <div class='text-center'>
      <%= image_tag '003-tongue-out.png', class: 'img-fluid mx-auto'  %>
    </div>
    <br/>
    <p>The machine is still learning...</p>
  </div>
</div>

app/views/visits/audio.html.erb
<%= render partial: 'visits/landing' %>

<section class="download bg-primary text-center" id="anchor">
  <div class="container">
    <h2 class="section-heading text-center"><i class="fa fa-headphones"></i>&nbsp;Step 2: Audio Test</h2>
    <div class="row">
      <div class='col-2'></div>
      <div class="col-4">
        <%= image_tag 'bird.png', class: 'img-fluid'  %>
      </div>
      <div class='col-4'>
        <div class="card">
          <div class="card-body text-left">
            <h4 class="card-title">Instructions</h4>
            <p>You will be played an audio file with varying frequencies. Use the audio check to adjust your volume. Press start test when you're ready.</p>
            <p>Every time you hear a sound press the button "Yes". If you stop hearing any sound, press "No".</p>
            <br/>
            <ul>
              <li>Use headphones</li>
              <li>Use low volume</li>
            </ul>
          </div>
        </div>
      </div>
      <div class='col-2'></div>
      <%= simple_form_for @visit, url: visit_audio_update_path, method: :post, html: { id: 'audio-form' } do |f| %>
      <%= f.input :audio_threshold %>
      <%= f.submit %>
      <% end %>
    </div><!-- row -->
    <div class='row' id='first-buttons'>
      <div class='col-2'></div>
      <div class='col-2'>
        <a href="javascript:audioCheck();" id='audio-check' class="btn btn-outline btn-xl">Audio Check</a>
      </div>
      <div class='col-2'>
        <a href="javascript:startTest();" id='start-test' class="btn btn-outline btn-xl">Start Test</a>
      </div>
    </div>
    <div class='row' id='second-buttons'>
      <div class='col-2'></div>
      <div class='col-2'>
        <a href="javascript:buttonYes();" id='button-yes' class="btn btn-outline btn-xl">Yes</a>
      </div>
      <div class='col-2'>
        <a href="javascript:buttonNo();" id='button-no' class="btn btn-outline btn-xl">No</a>
      </div>
    </div>
  </div>
</section>

app/views/visits/index.html.erb
<%= render partial: 'visits/landing' %>

<section class="download bg-primary text-center" id="download">
  <div class="container" id='single-page'>
    <h2 class="section-heading text-center"><i class="fa fa-camera-retro"></i>&nbsp;Step 1: Upload your selfie</h2>
    <div class="row justify-content-center">
      <div class="col-4">
        <%= simple_form_for @visit,  url: photo_visits_path, method: :post do |i| %>
          <%= i.label :photo_file do %>
            <%= image_tag 'avatar-default.png', class: 'img-fluid' %>
          <% end %>
          <span style="display:none;">
            <%= i.file_field :photo_file, html: { hidden: true } %>
          </span>

          <%= i.hidden_field :uuid %>
          <br/>
          <%= i.submit 'Upload Selfie', class: 'btn btn-outline btn-xl' %>
        <% end %>
      </div>
      <div class='col-3'>
        <ul class='list-group'>
          <li class='list-group-item lead text-muted'>headshot</li>
          <li class='list-group-item lead text-muted'>no glasses</li>
          <li class='list-group-item lead text-muted'>no head covering</li>
          <li class='list-group-item lead text-muted'>no gadgets</li>
          <li class='list-group-item lead text-muted'>good lighting</li>
          <li class='list-group-item lead text-muted'>square aspect</li>
        </ul>
      </div>
    </div>
  </div>
</section>






<%#= render partial: 'visits/picture' %>

<%#= render partial: 'visits/questions' %>

<%#= render partial: 'visits/sound' %>

 <section class="contact bg-primary" id="contact">
   <div class="container">
     <ul class="list-inline list-social">
       <li class="list-inline-item social-twitter">
         <a href="#">
           <i class="fa fa-twitter"></i>
         </a>
       </li>
       <li class="list-inline-item social-facebook">
         <a href="#">
           <i class="fa fa-facebook"></i>
         </a>
       </li>
       <li class="list-inline-item social-google-plus">
         <a href="#">
           <i class="fa fa-google-plus"></i>
         </a>
       </li>
     </ul>
   </div>
 </section>

app/views/visits/questions.html.erb
<%= render partial: 'visits/landing' %>

<section class="download bg-primary text-center" id="anchor">
  <div class="container">
    <div class="row">
      <div class="col-md-8 mx-auto">
        <h2 class="section-heading">Tell us about yourself</h2>
        <%= simple_form_for @visit,
                            url: visit_questions_update_path,
                            method: :post,
                            id: 'question-form' do |f| %>
          <div class='row'>
            <div class='col-3'></div>
            <div class='col-6'>
              <%= f.input :age, label: 'Your age' %>
            </div>
            <div class='col-3'></div>
          </div>
          <div class='row'>
            <div class='col-3'></div>
            <div class='col-6'>
              <label>Nationality</label>
              <%= f.country_select :nationality, label: 'Nationality' %>
            </div>
            <div class='col-3'></div>
          </div>
          <%= f.input :gender, as: :radio_buttons, collection: ["Male", "Female","Other"], label: false %>
          <div class='row'>
            <div class='col-6'>
              <label>Mother's origin</label>
              <%= f.country_select :mother_origin, { :class => "form-control" } %>
            </div>
            <div class='col-6'>
              <label>Father's origin</label>
              <%= f.country_select :father_origin, { :class => "form-control" } %>
            </div>
          </div>
          <%= f.input :hearing_impaired, as: :radio_buttons, collection: ["Yes", "No"] %>
          <%= f.hidden_field :uuid %>
          <%= f.submit 'Go', class: 'btn btn-outline btn-xl' %>
        <% end %>

        <div class="badges">
          <a class="badge-link" href="#"><img src="img/google-play-badge.svg" alt=""></a>
          <a class="badge-link" href="#"><img src="img/app-store-badge.svg" alt=""></a>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/visits/result.html.erb
<%= render partial: 'visits/landing' %>

<section class="download bg-primary text-center" id="anchor">
  <h2 class="section-heading text-center"><i class="fa fa-id-card-o"></i>&nbsp;Results: You look like...</h2>
  <div class="row">
    <div class='col-2'></div>
    <div class="col-4">
      <%= image_tag @visit.photo_file, class: 'img-fluid'  %>
      <p>You are contributer <%= @visit.id %>. Thank you for your help!</p>
    </div>
    <div class='col-4'>
      <% case @visit.result %>
      <% when 'good' %>
        <%= render 'visits/result_good' %>
      <% when 'bad' %>
        <%= render 'visits/result_bad' %>
      <% when 'ugly' %>
        <%= render 'visits/result_ugly' %>
      <% end %>
    </div>
    <div class='col-2'></div>
  </div><!-- row -->
</section>